Settings:
  Enabled: true
  Name: '&cAutoSmelter'
  MaxLevel: 10
  MaxStack: 10
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7chance to Smelt ores you mine'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cAutoSmelter + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe AutoSmelter level by %Level%'
