Settings:
  Enabled: true
  Name: '&cBeaconDiscover'
  MaxLevel: 2
  MaxStack: 100
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your BeaconDiscover level'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cBeaconDiscover + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe BeaconDiscover level by %Level%'
