Settings:
  Enabled: true
  Name: '&cBlessing'
  MaxLevel: 10
  MaxStack: 100
  Requirement:
    Enabled: true
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your Blessing level'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cBlessing + %Level%'
    Lore:
    - '&1Unique Shard Require pickaxe level 10'
    - '&7Increase your pickaxe Blessing level by %Level% '
    - '&7Stack up to 100 level '
