Settings:
  Enabled: true
  Name: '&cEfficiency'
  MaxLevel: 10
  MaxStack: 100
  Real: true
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Efficiency'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cEfficiency + %Level%'
    Lore:
    - '&1Unique Shard RequiredLevel %RequiredLevel%'
    - '&7Increase your pickaxe Efficiency by %Level%'
    - '&7Stack up to %MaxStack%'
