Settings:
  Enabled: true
  Name: '&cFly'
  MaxLevel: 1
  MaxStack: 2
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Give you ability to fly'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cFly + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Give you ability to fly '
    - '&7And increase the speed 0.1 * %Level%'
