Settings:
  Enabled: true
  Name: '&cHaste'
  MaxLevel: 1
  MaxStack: 2
  Real: true
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Haste'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cHaste + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe Haste level by %Level%'
