Settings:
  Enabled: true
  Name: '&cItemsCollector'
  MaxLevel: 2
  MaxStack: 100
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your ItemsCollector level'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cItemsCollector + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe ItemsCollector level by %Level%'
