Settings:
  Enabled: true
  Name: '&cJumpBoost'
  MaxLevel: 3
  MaxStack: 3
  Real: true
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Efficiency'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cJumpBoost + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe cHaste level by %Level%'
