Settings:
  Enabled: true
  Name: '&cLuck'
  MaxLevel: 2
  MaxStack: 10
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Luck'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cLuck + %Level%'
    Lore:
    - '&1Unique Shard RequiredLevel %RequiredLevel%'
    - '&7Increase your pickaxe Luck level by %Level%'
