Settings:
  Enabled: true
  Name: '&cMomentum'
  MaxLevel: 10
  MaxStack: 10
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Momentum level by'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cMomentum + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe Momentum level by %Level%'
    - '&7MaxStack 10 Levels'
