Settings:
  Enabled: true
  Name: '&cSellMultiplier'
  MaxLevel: 2
  MaxStack: 6
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe SellMultiplier'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cSellMultiplier + %Level%'
    Lore:
    - '&1Unique Shard RequiredLevel %RequiredLevel%'
    - '&7Increase your pickaxe SellMultiplier level by %Level%'
