Settings:
  Enabled: true
  Name: '&cThorHammer'
  MaxLevel: 2
  MaxStack: 5
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your ThorHammer level'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cThorHammer + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe ThorHammer level by %Level%'
