Settings:
  Enabled: true
  Name: '&cTokenDiscover'
  MaxLevel: 10
  MaxStack: 100
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your TokenDiscover level'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cTokenDiscover + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe TokenDiscover level by %Level%'
