Settings:
  Enabled: true
  Name: '&cTransfuse'
  MaxLevel: 10
  MaxStack: 10
  Requirement:
    Enabled: false
    Number: 10
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7gives you Transfuse effect'
  Shard:
    Item:
      ==: org.bukkit.inventory.ItemStack
      type: PRISMARINE_SHARD
    Glow: true
    Name: '&cTransfuse + %Level%'
    Lore:
    - '&1Unique Shard  '
    - '&7Increase your pickaxe Transfuse level by %Level%'
