# [ RevAutoSell required]
Settings:
  Enabled: true
  InGui: true
  Name: AutoSell
  Colour: '&7'
  Slot: 30
  MaxLevel: 100
  Currency: RevToken
  Cost: 10000
  Increase-Cost-by: 5000
  Chance: 1
  Increase-Chance-by: 1
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7a chance to sell drops and inventory chance depend on level'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  Message:
    Enabled: false
    Bar: true
    Format: '&7AutoSell'
