Settings:
  Enabled: true
  InGui: true
  Name: Blessing
  Colour: '&7'
  Slot: 10
  MaxLevel: 100
  Max: 10
  Min: 1
  GiveCurrency: RevToken
  MultiBreak: true
  MultiBreakMaxSuccess: 1000
  EnchantNeeded: false
  Currency: RevToken
  Cost: 1000
  Increase-Cost-by: 1000
  Chance: 1
  Increase-Chance-by: 0.01
  Requirement:
    Enabled: true
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Chance to get more Tokens and give everyone online%nl%as you mine
    the chance depend on the level%nl% This Enchants Require pickaxe level 10 %nl%To
    be able to purchase'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  Message:
    Enabled: true
    Bar: true
    '1': '&7you got %amount% tokens from Blessing'
    '2': '&7%from player% gived you %amount% tokens from Blessing'
