Settings:
  Enabled: true
  InGui: true
  Name: Charity
  Colour: '&7'
  Slot: 11
  MaxLevel: 100
  Max: 10
  Min: 1
  GiveCurrency: Vault
  MultiBreak: true
  MultiBreakMaxSuccess: 1000
  EnchantNeeded: false
  Currency: RevToken
  Cost: 1000
  Increase-Cost-by: 1000
  Chance: 1
  Increase-Chance-by: 0.01
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Chance to get more money and give everyone online%nl%as you mine
    the chance depend on the level'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  Message:
    Enabled: true
    Bar: true
    '1': '&7you got %amount% $ from Charity'
    '2': '&7%from player% gived you %amount% $ from Charity'
