Settings:
  Enabled: true
  InGui: true
  Name: Efficiency
  Colour: '&7'
  Slot: 12
  MaxLevel: 100
  Currency: Vault
  Cost: 1000
  Increase-Cost-by: 1000
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Efficiency lol'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
