Settings:
  Enabled: true
  InGui: true
  Name: EnergyCollector
  Colour: '&7'
  Slot: 13
  MaxLevel: 100
  MultiBreak: true
  MultiBreakMaxSuccess: 1000
  Energy:
    Max: 10
    Min: 1
  Currency: RevToken
  Cost: 1000
  Increase-Cost-by: 1000
  Chance: 3
  Increase-Chance-by: 0.1
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Energy'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  Message:
    Enabled: false
    Bar: true
    Format: '&7EnergyCollector %Amount_FormattedA%'
