Settings:
  Enabled: true
  InGui: true
  Name: Explosive
  Colour: '&7'
  Slot: 14
  MaxLevel: 10
  Radius-1: 2
  Radius-2: 2
  Radius-3: 2
  Currency: RevToken
  Cost: 1000
  Increase-Cost-by: 1000
  Chance: 100
  Increase-Chance-by: 0.1
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Sound:
    Enabled: true
    ID: ENTITY_GENERIC_EXPLODE
    Volume: 1
    Pitch: 1
  Description: '&7Break 3 * 3 area'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  IgnoreBlocks:
  - BEDROCK
  Message:
    Enabled: true
    Bar: true
    Format: '&7Explosive %Amount_FormattedA% Blocks'
