Settings:
  Enabled: true
  InGui: true
  Name: JumpBoost
  Colour: '&7'
  Slot: 21
  MaxLevel: 3
  Currency: RevToken
  Cost: 10000
  Increase-Cost-by: 1000
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7gives you JumpBoost effect'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  WorldsBlockList:
  - pvp
  - pvp2
