# [
#  ]
Settings:
  Enabled: true
  InGui: true
  Name: Laser
  Colour: '&7'
  Slot: 43
  MaxLevel: 10
  Currency: RevToken
  Cost: 1000
  Increase-Cost-by: 1000
  Chance: 100
  Increase-Chance-by: 0.1
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Sound:
    Enabled: true
    ID: BLOCK_SNOW_BREAK
    Volume: 1
    Pitch: 1
  Description: '&7remove Lines from the mine'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  Message:
    Enabled: true
    Bar: true
    Format: '&7Laser %Amount_FormattedA% Blocks'
