# [ how Luck works, 
#  so if chance of Luck is Chance + Level * Increase-Chance-by, 
#  the chance of Level 10 is 20 + 10 * 0.1 = 21% Chance, 
#  to apply Luck effect to the Enchants.  , 
#  then  the chance of the enchants +  LuckLevel *  Increase-Chance-by-Level  <option>, 
#   so if Enchant chance is 5% + 10 <LuckLevel> * 0.01 <Increase-Chance-by-Level  <option>>, 
#   chance will be 5.1%, 
#  so Luck will Increase the chance of Enchant this is how it works]
Settings:
  Enabled: true
  InGui: true
  Name: Luck
  Colour: '&7'
  Slot: 33
  MaxLevel: 100
  Currency: RevToken
  Cost: 10000
  Increase-Cost-by: 5000
  Chance: 20
  Increase-Chance-by: 0.1
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase the chance of all Enchants on your pickaxe%nl%&7 chance
    depend on level'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  Increase-Chance-by-Level:
    KeysDiscover: 0.01
    ItemsCollector: 0.01
    SpareChange: 0.01
    Haste: 0.01
    Fly: 0.01
    Explosive: 0.01
    SellMultiplier: 0.01
    Efficiency: 0.01
    JumpBoost: 0.01
    Transfuse: 0.01
    Unbreaking: 0.01
    AutoSell: 0.01
    AutoSmelter: 0.01
    NightVision: 0.01
    Speed: 0.01
    EnergyCollector: 0.01
    Momentum: 0.01
    CoinDiscover: 0.01
    CratesFinder: 0.01
    ThorHammer: 0.01
    BeaconDiscover: 0.01
    Experience: 0.01
    Blessing: 0.01
    Luck: 0.01
    Laser: 0.01
    Fortune: 0.01
    JackHammer: 0.01
    Charity: 0.01
    TokenDiscover: 0.01
    MeteorShower: 0.01
