Settings:
  Enabled: true
  InGui: true
  Name: NightVision
  Colour: '&7'
  Slot: 23
  MaxLevel: 1
  Currency: RevToken
  Cost: 1000000
  Increase-Cost-by: 1000
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7gives you NightVision effect'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  WorldsBlockList:
  - pvp
  - pvp2
