# [ RevAutoSell required]
Settings:
  Enabled: true
  InGui: true
  Name: SellMultiplier
  Colour: '&7'
  Slot: 31
  MaxLevel: 10
  Currency: RevToken
  Cost: 10000
  Increase-Cost-by: 10000
  Chance: 100
  Increase-Chance-by: 0
  Multiplier: 0.1
  Increase-Multiplier-by: 0.1
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Selling Multiplier%nl%&7 work just with autosell
    enchants / shard'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  Message:
    Enabled: false
    Bar: true
    Format: '&7SellMultiplier + %Amount% '
