Settings:
  Enabled: true
  InGui: true
  Name: SpareChange
  Colour: '&7'
  Slot: 24
  MaxLevel: 10
  Max: 10
  Min: 1
  MultiBreak: true
  MultiBreakMaxSuccess: 1000
  GiveCurrency: Vault
  Currency: RevToken
  Cost: 1000
  Increase-Cost-by: 1000
  Chance: 2
  Increase-Chance-by: 0.1
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Chance to get more money%nl%&7as you mine the chance depend on the
    level'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  Message:
    Enabled: false
    Bar: true
    Format: '&7SpareChange + %Amount_FormattedA% '
