Settings:
  Enabled: true
  InGui: true
  Name: Speed
  Colour: '&7'
  Slot: 25
  Effect: false
  Increase-Walk-speed-by: 0.01
  MaxLevel: 10
  Currency: RevToken
  Cost: 10000
  Increase-Cost-by: 10000
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7gives you JumpBoost effect'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
  WorldsBlockList:
  - pvp
  - pvp2
