Settings:
  Enabled: true
  InGui: true
  Real: false
  Name: Unbreaking
  Colour: '&7'
  Slot: 29
  MaxLevel: 100
  Increase-by-level: 1000
  Currency: Vault
  Cost: 1000
  Increase-Cost-by: 1000
  Requirement:
    Enabled: false
    Number: 5
    Placeholder: '%RevEnchants_Tool_Flag_Level%'
  Description: '&7Increase your pickaxe Durability'
  Book:
    ==: org.bukkit.inventory.ItemStack
    type: BOOK
