Settings:
  Placeholder: false
  PerformanceOverQuality:
    Enabled: false
    EverySeconds: 5
Lore:
- '&2&lShards:'
- ' '
- '%Rev_Shard_1_Name% %Rev_Shard_1_Level%'
- '%Rev_Shard_2_Name% %Rev_Shard_2_Level_Formatted%'
- '%Rev_Shard_3_Name% %Rev_Shard_3_Level_Roman%'
- '%Rev_Shard_4_Name% %Rev_Shard_4_Level%'
- '%Rev_Shard_5_Name% %Rev_Shard_5_Level_Roman%'
- '%Rev_Shard_6_Name% %Rev_Shard_6_Level%'
- '&f&lStats:'
- ' '
- '&fOwner &c%Rev_Flag_Owner_String%'
- '&6Blocks %Rev_Flag_Blocks_Formatted%'
- '&6Energy %Rev_Flag_Energy_Formatted% / %Rev_Flag_MaxEnergy_Formatted% '
- '%Rev_Energy_Progress% %Rev_Energy_Percentage%% '
- '&eDurability %Rev_Flag_Durability_Formatted% / %Rev_Flag_MaxDurability_Formatted% '
- '%Rev_Durability_Progress% %Rev_Durability_Percentage%% '
- '&6Level %Rev_Flag_Level_Formatted% / %Rev_Flag_MaxLevel_Formatted%'
- '&6Shard Slots %Rev_Flag_Shards_Slots% / %Rev_Flag_MaxShards_Slots%'
- '&6Enchants Slots &f%Rev_Flag_UsedEnchants_Slots% &3OF &8%Rev_Flag_MaxEnchants_Slots%
  &3And &f%Rev_Flag_Enchants_Slots% FREE'
- '&7&lEnchantments:'
- ' '
- '%Rev_Enchant_Blessing_Colour%%Rev_Enchant_Blessing_Name% &f%Rev_Enchant_Blessing_Level%'
- '%Rev_Enchant_Charity_Colour%%Rev_Enchant_Charity_Name% &f%Rev_Enchant_Charity_Level%'
- '%Rev_Enchant_Efficiency_Colour%%Rev_Enchant_Efficiency_Name% &f%Rev_Enchant_Efficiency_Level%'
- '%Rev_Enchant_EnergyCollector_Colour%%Rev_Enchant_EnergyCollector_Name% &f%Rev_Enchant_EnergyCollector_Level%'
- '%Rev_Enchant_Explosive_Colour%%Rev_Enchant_Explosive_Name% &f%Rev_Enchant_Explosive_Level%'
- '%Rev_Enchant_Fly_Colour%%Rev_Enchant_Fly_Name% &f%Rev_Enchant_Fly_Level%'
- '%Rev_Enchant_Fortune_Colour%%Rev_Enchant_Fortune_Name% &f%Rev_Enchant_Fortune_Level%'
- '%Rev_Enchant_Haste_Colour%%Rev_Enchant_Haste_Name% &f%Rev_Enchant_Haste_Level%'
- '%Rev_Enchant_JackHammer_Colour%%Rev_Enchant_JackHammer_Name% &f%Rev_Enchant_JackHammer_Level%'
- '%Rev_Enchant_JumpBoost_Colour%%Rev_Enchant_JumpBoost_Name% &f%Rev_Enchant_JumpBoost_Level%'
- '%Rev_Enchant_KeysDiscover_Colour%%Rev_Enchant_KeysDiscover_Name% &f%Rev_Enchant_KeysDiscover_Level%'
- '%Rev_Enchant_NightVision_Colour%%Rev_Enchant_NightVision_Name% &f%Rev_Enchant_NightVision_Level%'
- '%Rev_Enchant_SpareChange_Colour%%Rev_Enchant_SpareChange_Name% &f%Rev_Enchant_SpareChange_Level%'
- '%Rev_Enchant_Speed_Colour%%Rev_Enchant_Speed_Name% &f%Rev_Enchant_Speed_Level%'
- '%Rev_Enchant_TokenDiscover_Colour%%Rev_Enchant_TokenDiscover_Name% &f%Rev_Enchant_TokenDiscover_Level%'
- '%Rev_Enchant_Unbreaking_Colour%%Rev_Enchant_Unbreaking_Name% &f%Rev_Enchant_Unbreaking_Level%'
- '%Rev_Enchant_Luck_Colour%%Rev_Enchant_Luck_Name% &f%Rev_Enchant_Luck_Level%'
- '%Rev_Enchant_SellMultiplier_Colour%%Rev_Enchant_SellMultiplier_Name% &f%Rev_Enchant_SellMultiplier_Level%'
- '%Rev_Enchant_AutoSell_Colour%%Rev_Enchant_AutoSell_Name% &f%Rev_Enchant_AutoSell_Level%'
- '%Rev_Enchant_CoinDiscover_Colour%%Rev_Enchant_CoinDiscover_Name% &f%Rev_Enchant_CoinDiscover_Level%'
- '%Rev_Enchant_Experience_Colour%%Rev_Enchant_Experience_Name% &f%Rev_Enchant_Experience_Level%'
- '%Rev_Enchant_CratesFinder_Colour%%Rev_Enchant_CratesFinder_Name% &f%Rev_Enchant_CratesFinder_Level%'
- '%Rev_Enchant_Transfuse_Colour%%Rev_Enchant_Transfuse_Name% &f%Rev_Enchant_Transfuse_Level%'
- '%Rev_Enchant_Momentum_Colour%%Rev_Enchant_Momentum_Name% &f%Rev_Enchant_Momentum_Level%'
- '%Rev_Enchant_BeaconDiscover_Colour%%Rev_Enchant_BeaconDiscover_Name% &f%Rev_Enchant_BeaconDiscover_Level%'
- '%Rev_Enchant_ItemsCollector_Colour%%Rev_Enchant_ItemsCollector_Name% &f%Rev_Enchant_ItemsCollector_Level%'
- '%Rev_Enchant_AutoSmelter_Colour%%Rev_Enchant_AutoSmelter_Name% &f%Rev_Enchant_AutoSmelter_Level%'
- '%Rev_Enchant_Laser_Colour%%Rev_Enchant_Laser_Name% &f%Rev_Enchant_Laser_Level%'
- '%Rev_Enchant_ThorHammer_Colour%%Rev_Enchant_ThorHammer_Name% &f%Rev_Enchant_ThorHammer_Level%'
- '%Rev_Enchant_MeteorShower_Colour%%Rev_Enchant_MeteorShower_Name% &f%Rev_Enchant_MeteorShower_Level%'
