Massage:
  '1': '&e&l(!) Hold your pickaxe'
  '2': '&c You are already at the maximum level!'
  '3': '&c - %Cost% %Currency_Name% %Currency_Symbol% for %NewLevels% levels'
  '4': '&c You don''t have the requirement to buy this Enchants!'
  '5': '&c You don''t have any empty Enchant slot!'
  '6': '&c you don''t have enough %Currency_Name% %Currency_Symbol%'
  '7': '&c you have %Currency_Amount% %Currency_Name% %Currency_Symbol%'
  '8': '&c %Player% have %Currency_Amount% %Currency_Name% %Currency_Symbol%'
  '9': '&e&l(!) &eYou don''t have the required permission'
  '10': '&e&l(!) &eyou don''t have enough %Currency_Name% %Currency_Symbol% to Withdraw'
  '11': '&a&l + %Currency_Amount% %Currency_Name% %Currency_Symbol%'
  '12': '&c&l - %Currency_Amount% %Currency_Name% %Currency_Symbol%'
  '13': '&e&l(!) &eRevEnchants Reloaded successfully&e.'
  '14': '&e&l(!) &ecan''t be enchanted!'
  '15': '&c Your pickaxe is MAX level !'
  '16': '&c Enchant slot has added to ur pickaxe!'
  '17': '&c Shard slot has added to ur pickaxe!'
  '18': '&c &eyou don''t have enough Energy to level up!'
  '19': '&c &eAuto level up has been enabled'
  '20': '&c &eAuto level up has been disabled!'
  '21': '&c &eyou have Max Enchant slot on your tool'
  '22': '&c &eyou have Max Shard slot on your tool'
  '23': '&e&l(!) &eyou don''t have enough Energy to Extract'
  '24': '&c You don''t have the requirement to use this shard!'
  '25': '&c you can''t afford repairing your pickaxe Cost %Currency_Amount% %Currency_Name%
    %Currency_Symbol%! &e&ltry beg for it in chat :) '
  '26': '&c -%Currency_Amount% %Currency_Name% %Currency_Symbol%  '
  '27': '&c &eAuto Repair has been enabled'
  '28': '&c &eAuto Repair has been disabled!'
  '29': '&c &eplease repair your pickaxe! /repair'
  '30': '&c &eyour tool already has Max durability'
  '31': '&c &eExplosive has been enabled'
  '32': '&c &eExplosive has been disabled!'
  '33': '&c &eJackHammer has been enabled'
  '34': '&c &eJackHammer has been disabled!'
  '35': '&c &eThorHammer has been enabled'
  '36': '&c &eThorHammer has been disabled!'
  '37': '&c &eLaser has been enabled'
  '38': '&c &eLaser has been disabled!'
